//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 02:15:18 PM CET 
//


package it.marcocarettoni.Footstar.xml.model.game;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import it.marcocarettoni.Footstar.xml.model.IModelXML;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="game" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="match_id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="season" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                   &lt;element name="played" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="round" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                   &lt;element name="home_team" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="home_team_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="home_city" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                   &lt;element name="away_team" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="away_team_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="away_city" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                   &lt;element name="home_goals" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                   &lt;element name="away_goals" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "game"
})
@XmlRootElement(name = "data")
public class Data {

    protected List<Data.Game> game;

    /**
     * Gets the value of the game property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the game property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGame().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Game }
     * 
     * 
     */
    public List<Data.Game> getGame() {
        if (game == null) {
            game = new ArrayList<Data.Game>();
        }
        return this.game;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="match_id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="season" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *         &lt;element name="played" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="round" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *         &lt;element name="home_team" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="home_team_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="home_city" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *         &lt;element name="away_team" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="away_team_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="away_city" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *         &lt;element name="home_goals" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *         &lt;element name="away_goals" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "matchId",
        "date",
        "season",
        "played",
        "type",
        "round",
        "homeTeam",
        "homeTeamId",
        "homeCity",
        "awayTeam",
        "awayTeamId",
        "awayCity",
        "homeGoals",
        "awayGoals"
    })
    public static class Game implements IModelXML {

        @XmlElement(name = "match_id")
        @XmlSchemaType(name = "unsignedInt")
        protected Long matchId;
        protected String date;
        @XmlSchemaType(name = "unsignedByte")
        protected Short season;
        @XmlSchemaType(name = "unsignedByte")
        protected Short played;
        protected String type;
        @XmlSchemaType(name = "unsignedByte")
        protected Short round;
        @XmlElement(name = "home_team")
        protected String homeTeam;
        @XmlElement(name = "home_team_id")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer homeTeamId;
        @XmlElement(name = "home_city")
        @XmlSchemaType(name = "unsignedByte")
        protected Short homeCity;
        @XmlElement(name = "away_team")
        protected String awayTeam;
        @XmlElement(name = "away_team_id")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer awayTeamId;
        @XmlElement(name = "away_city")
        @XmlSchemaType(name = "unsignedByte")
        protected Short awayCity;
        @XmlElement(name = "home_goals")
        @XmlSchemaType(name = "unsignedByte")
        protected Short homeGoals;
        @XmlElement(name = "away_goals")
        @XmlSchemaType(name = "unsignedByte")
        protected Short awayGoals;

        /**
         * Gets the value of the matchId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getMatchId() {
            return matchId;
        }

        /**
         * Sets the value of the matchId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setMatchId(Long value) {
            this.matchId = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the season property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getSeason() {
            return season;
        }

        /**
         * Sets the value of the season property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setSeason(Short value) {
            this.season = value;
        }

        /**
         * Gets the value of the played property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getPlayed() {
            return played;
        }

        /**
         * Sets the value of the played property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setPlayed(Short value) {
            this.played = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the round property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getRound() {
            return round;
        }

        /**
         * Sets the value of the round property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setRound(Short value) {
            this.round = value;
        }

        /**
         * Gets the value of the homeTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeam() {
            return homeTeam;
        }

        /**
         * Sets the value of the homeTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeam(String value) {
            this.homeTeam = value;
        }

        /**
         * Gets the value of the homeTeamId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeTeamId() {
            return homeTeamId;
        }

        /**
         * Sets the value of the homeTeamId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeTeamId(Integer value) {
            this.homeTeamId = value;
        }

        /**
         * Gets the value of the homeCity property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getHomeCity() {
            return homeCity;
        }

        /**
         * Sets the value of the homeCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setHomeCity(Short value) {
            this.homeCity = value;
        }

        /**
         * Gets the value of the awayTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeam() {
            return awayTeam;
        }

        /**
         * Sets the value of the awayTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeam(String value) {
            this.awayTeam = value;
        }

        /**
         * Gets the value of the awayTeamId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayTeamId() {
            return awayTeamId;
        }

        /**
         * Sets the value of the awayTeamId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayTeamId(Integer value) {
            this.awayTeamId = value;
        }

        /**
         * Gets the value of the awayCity property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getAwayCity() {
            return awayCity;
        }

        /**
         * Sets the value of the awayCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setAwayCity(Short value) {
            this.awayCity = value;
        }

        /**
         * Gets the value of the homeGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getHomeGoals() {
            return homeGoals;
        }

        /**
         * Sets the value of the homeGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setHomeGoals(Short value) {
            this.homeGoals = value;
        }

        /**
         * Gets the value of the awayGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getAwayGoals() {
            return awayGoals;
        }

        /**
         * Sets the value of the awayGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setAwayGoals(Short value) {
            this.awayGoals = value;
        }
        
    	@Override
    	public Long getIDRow() {
    		return getMatchId() != null ? getMatchId() : 0L; 
    	}

    }

}
