//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.09 at 11:51:46 PM CET 
//


package it.marcocarettoni.Footstar.xml.model.denominazioni;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.marcocarettoni.Footstar.xmlModel.denominazioni package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.marcocarettoni.Footstar.xmlModel.denominazioni
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Data.MentalSkills }
     * 
     */
    public Data.MentalSkills createDataMentalSkills() {
        return new Data.MentalSkills();
    }

    /**
     * Create an instance of {@link Data.Future }
     * 
     */
    public Data.Future createDataFuture() {
        return new Data.Future();
    }

    /**
     * Create an instance of {@link Data.Sides }
     * 
     */
    public Data.Sides createDataSides() {
        return new Data.Sides();
    }

    /**
     * Create an instance of {@link Data.Positions }
     * 
     */
    public Data.Positions createDataPositions() {
        return new Data.Positions();
    }

    /**
     * Create an instance of {@link Data.PlayerExperience }
     * 
     */
    public Data.PlayerExperience createDataPlayerExperience() {
        return new Data.PlayerExperience();
    }

    /**
     * Create an instance of {@link Data.Cities }
     * 
     */
    public Data.Cities createDataCities() {
        return new Data.Cities();
    }

    /**
     * Create an instance of {@link Data.Countries }
     * 
     */
    public Data.Countries createDataCountries() {
        return new Data.Countries();
    }

    /**
     * Create an instance of {@link Data.Languages }
     * 
     */
    public Data.Languages createDataLanguages() {
        return new Data.Languages();
    }

    /**
     * Create an instance of {@link Data.Trainings }
     * 
     */
    public Data.Trainings createDataTrainings() {
        return new Data.Trainings();
    }

    /**
     * Create an instance of {@link Data.DatabaseData }
     * 
     */
    public Data.DatabaseData createDataDatabaseData() {
        return new Data.DatabaseData();
    }

    /**
     * Create an instance of {@link Data.MentalSkills.Skill }
     * 
     */
    public Data.MentalSkills.Skill createDataMentalSkillsSkill() {
        return new Data.MentalSkills.Skill();
    }

    /**
     * Create an instance of {@link Data.Future.Future }
     * 
     */
    public Data.Future.Future2 createDataFutureFuture() {
        return new Data.Future.Future2();
    }

    /**
     * Create an instance of {@link Data.Sides.Side }
     * 
     */
    public Data.Sides.Side createDataSidesSide() {
        return new Data.Sides.Side();
    }

    /**
     * Create an instance of {@link Data.Positions.Position }
     * 
     */
    public Data.Positions.Position createDataPositionsPosition() {
        return new Data.Positions.Position();
    }

    /**
     * Create an instance of {@link Data.PlayerExperience.ExpItem }
     * 
     */
    public Data.PlayerExperience.ExpItem createDataPlayerExperienceExpItem() {
        return new Data.PlayerExperience.ExpItem();
    }

    /**
     * Create an instance of {@link Data.Cities.City }
     * 
     */
    public Data.Cities.City createDataCitiesCity() {
        return new Data.Cities.City();
    }

    /**
     * Create an instance of {@link Data.Countries.Country }
     * 
     */
    public Data.Countries.Country createDataCountriesCountry() {
        return new Data.Countries.Country();
    }

    /**
     * Create an instance of {@link Data.Languages.LanguageItem }
     * 
     */
    public Data.Languages.LanguageItem createDataLanguagesLanguageItem() {
        return new Data.Languages.LanguageItem();
    }

    /**
     * Create an instance of {@link Data.Trainings.TrainingItem }
     * 
     */
    public Data.Trainings.TrainingItem createDataTrainingsTrainingItem() {
        return new Data.Trainings.TrainingItem();
    }

}
