//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 10:00:56 AM CET 
//


package it.marcocarettoni.Footstar.xml.model.player;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.marcocarettoni.Footstar.xml.model.player package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.marcocarettoni.Footstar.xml.model.player
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link Player.NationalTeams }
     * 
     */
    public Player.NationalTeams createPlayerNationalTeams() {
        return new Player.NationalTeams();
    }

    /**
     * Create an instance of {@link Player.Talents }
     * 
     */
    public Player.Talents createPlayerTalents() {
        return new Player.Talents();
    }

    /**
     * Create an instance of {@link Player.Adaptabilities }
     * 
     */
    public Player.Adaptabilities createPlayerAdaptabilities() {
        return new Player.Adaptabilities();
    }

    /**
     * Create an instance of {@link Player.Position }
     * 
     */
    public Player.Position createPlayerPosition() {
        return new Player.Position();
    }

    /**
     * Create an instance of {@link Player.SideLeft }
     * 
     */
    public Player.SideLeft createPlayerSideLeft() {
        return new Player.SideLeft();
    }

    /**
     * Create an instance of {@link Player.SideRight }
     * 
     */
    public Player.SideRight createPlayerSideRight() {
        return new Player.SideRight();
    }

    /**
     * Create an instance of {@link Player.SideCenter }
     * 
     */
    public Player.SideCenter createPlayerSideCenter() {
        return new Player.SideCenter();
    }

    /**
     * Create an instance of {@link Player.BirthCity }
     * 
     */
    public Player.BirthCity createPlayerBirthCity() {
        return new Player.BirthCity();
    }

    /**
     * Create an instance of {@link Player.Injured }
     * 
     */
    public Player.Injured createPlayerInjured() {
        return new Player.Injured();
    }

    /**
     * Create an instance of {@link Player.Suspended }
     * 
     */
    public Player.Suspended createPlayerSuspended() {
        return new Player.Suspended();
    }

    /**
     * Create an instance of {@link Player.SuspendedInt }
     * 
     */
    public Player.SuspendedInt createPlayerSuspendedInt() {
        return new Player.SuspendedInt();
    }

    /**
     * Create an instance of {@link Player.Future }
     * 
     */
    public Player.Future createPlayerFuture() {
        return new Player.Future();
    }

    /**
     * Create an instance of {@link Player.Confidence }
     * 
     */
    public Player.Confidence createPlayerConfidence() {
        return new Player.Confidence();
    }

    /**
     * Create an instance of {@link Player.Experience }
     * 
     */
    public Player.Experience createPlayerExperience() {
        return new Player.Experience();
    }

    /**
     * Create an instance of {@link Player.Value }
     * 
     */
    public Player.Value createPlayerValue() {
        return new Player.Value();
    }

    /**
     * Create an instance of {@link Player.Wage }
     * 
     */
    public Player.Wage createPlayerWage() {
        return new Player.Wage();
    }

    /**
     * Create an instance of {@link Player.WeeklyTraining }
     * 
     */
    public Player.WeeklyTraining createPlayerWeeklyTraining() {
        return new Player.WeeklyTraining();
    }

    /**
     * Create an instance of {@link Player.DoubleNat }
     * 
     */
    public Player.DoubleNat createPlayerDoubleNat() {
        return new Player.DoubleNat();
    }

    /**
     * Create an instance of {@link Player.NationalTeams.Country }
     * 
     */
    public Player.NationalTeams.Country createPlayerNationalTeamsCountry() {
        return new Player.NationalTeams.Country();
    }

    /**
     * Create an instance of {@link Player.Talents.Talent }
     * 
     */
    public Player.Talents.Talent createPlayerTalentsTalent() {
        return new Player.Talents.Talent();
    }

    /**
     * Create an instance of {@link Player.Adaptabilities.Adaptability }
     * 
     */
    public Player.Adaptabilities.Adaptability createPlayerAdaptabilitiesAdaptability() {
        return new Player.Adaptabilities.Adaptability();
    }

}
