//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 05:57:01 PM CET 
//


package it.marcocarettoni.Footstar.xml.model.team;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.marcocarettoni.Footstar.xml.model.team package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TeamDataTeamPlayersPlayerFavoriteFoot_QNAME = new QName("", "favorite_foot");
    private final static QName _TeamDataTeamPlayersPlayerTransferList_QNAME = new QName("", "transfer_list");
    private final static QName _TeamDataTeamPlayersPlayerStrength_QNAME = new QName("", "strength");
    private final static QName _TeamDataTeamPlayersPlayerBirthMonth_QNAME = new QName("", "birth_month");
    private final static QName _TeamDataTeamPlayersPlayerRelease_QNAME = new QName("", "release");
    private final static QName _TeamDataTeamPlayersPlayerShortPasses_QNAME = new QName("", "short_passes");
    private final static QName _TeamDataTeamPlayersPlayerTeamId_QNAME = new QName("", "team_id");
    private final static QName _TeamDataTeamPlayersPlayerFlair_QNAME = new QName("", "flair");
    private final static QName _TeamDataTeamPlayersPlayerExperience_QNAME = new QName("", "experience");
    private final static QName _TeamDataTeamPlayersPlayerCrosses_QNAME = new QName("", "crosses");
    private final static QName _TeamDataTeamPlayersPlayerConsistency_QNAME = new QName("", "consistency");
    private final static QName _TeamDataTeamPlayersPlayerBirthYear_QNAME = new QName("", "birth_year");
    private final static QName _TeamDataTeamPlayersPlayerInfluence_QNAME = new QName("", "influence");
    private final static QName _TeamDataTeamPlayersPlayerReflexes_QNAME = new QName("", "reflexes");
    private final static QName _TeamDataTeamPlayersPlayerAcceleration_QNAME = new QName("", "acceleration");
    private final static QName _TeamDataTeamPlayersPlayerOutOfArea_QNAME = new QName("", "out_of_area");
    private final static QName _TeamDataTeamPlayersPlayerFirstTouch_QNAME = new QName("", "first_touch");
    private final static QName _TeamDataTeamPlayersPlayerFitness_QNAME = new QName("", "fitness");
    private final static QName _TeamDataTeamPlayersPlayerLongShots_QNAME = new QName("", "long_shots");
    private final static QName _TeamDataTeamPlayersPlayerPlayerName_QNAME = new QName("", "player_name");
    private final static QName _TeamDataTeamPlayersPlayerCreativity_QNAME = new QName("", "creativity");
    private final static QName _TeamDataTeamPlayersPlayerSkillsWeek_QNAME = new QName("", "skills_week");
    private final static QName _TeamDataTeamPlayersPlayerNewBirthYear_QNAME = new QName("", "new_birth_year");
    private final static QName _TeamDataTeamPlayersPlayerWage_QNAME = new QName("", "wage");
    private final static QName _TeamDataTeamPlayersPlayerGoals_QNAME = new QName("", "goals");
    private final static QName _TeamDataTeamPlayersPlayerSideLeft_QNAME = new QName("", "side_left");
    private final static QName _TeamDataTeamPlayersPlayerAssistsCareer_QNAME = new QName("", "assists_career");
    private final static QName _TeamDataTeamPlayersPlayerLastLogin_QNAME = new QName("", "last_login");
    private final static QName _TeamDataTeamPlayersPlayerAdapt_QNAME = new QName("", "adapt");
    private final static QName _TeamDataTeamPlayersPlayerContract_QNAME = new QName("", "contract");
    private final static QName _TeamDataTeamPlayersPlayerSuspendedInt_QNAME = new QName("", "suspended_int");
    private final static QName _TeamDataTeamPlayersPlayerSideCenter_QNAME = new QName("", "side_center");
    private final static QName _TeamDataTeamPlayersPlayerTeamName_QNAME = new QName("", "team_name");
    private final static QName _TeamDataTeamPlayersPlayerSuspended_QNAME = new QName("", "suspended");
    private final static QName _TeamDataTeamPlayersPlayerRegistrationDate_QNAME = new QName("", "registration_date");
    private final static QName _TeamDataTeamPlayersPlayerNationality_QNAME = new QName("", "nationality");
    private final static QName _TeamDataTeamPlayersPlayerUserId_QNAME = new QName("", "user_id");
    private final static QName _TeamDataTeamPlayersPlayerGoalsCareer_QNAME = new QName("", "goals_career");
    private final static QName _TeamDataTeamPlayersPlayerPosition_QNAME = new QName("", "position");
    private final static QName _TeamDataTeamPlayersPlayerNtSquad_QNAME = new QName("", "nt_squad");
    private final static QName _TeamDataTeamPlayersPlayerAgility_QNAME = new QName("", "agility");
    private final static QName _TeamDataTeamPlayersPlayerCommandOfArea_QNAME = new QName("", "command_of_area");
    private final static QName _TeamDataTeamPlayersPlayerLoanTo_QNAME = new QName("", "loan_to");
    private final static QName _TeamDataTeamPlayersPlayerTackling_QNAME = new QName("", "tackling");
    private final static QName _TeamDataTeamPlayersPlayerBirthCity_QNAME = new QName("", "birth_city");
    private final static QName _TeamDataTeamPlayersPlayerDoubleNat_QNAME = new QName("", "double_nat");
    private final static QName _TeamDataTeamPlayersPlayerJumping_QNAME = new QName("", "jumping");
    private final static QName _TeamDataTeamPlayersPlayerComposure_QNAME = new QName("", "composure");
    private final static QName _TeamDataTeamPlayersPlayerLoanFrom_QNAME = new QName("", "loan_from");
    private final static QName _TeamDataTeamPlayersPlayerLastContractDate_QNAME = new QName("", "last_contract_date");
    private final static QName _TeamDataTeamPlayersPlayerTechnique_QNAME = new QName("", "technique");
    private final static QName _TeamDataTeamPlayersPlayerSetPieces_QNAME = new QName("", "set_pieces");
    private final static QName _TeamDataTeamPlayersPlayerLongPasses_QNAME = new QName("", "long_passes");
    private final static QName _TeamDataTeamPlayersPlayerDateLastTraining_QNAME = new QName("", "date_last_training");
    private final static QName _TeamDataTeamPlayersPlayerSpeed_QNAME = new QName("", "speed");
    private final static QName _TeamDataTeamPlayersPlayerGameVision_QNAME = new QName("", "game_vision");
    private final static QName _TeamDataTeamPlayersPlayerYouthTeam_QNAME = new QName("", "youth_team");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTraining_QNAME = new QName("", "weekly_training");
    private final static QName _TeamDataTeamPlayersPlayerFinishing_QNAME = new QName("", "finishing");
    private final static QName _TeamDataTeamPlayersPlayerThrowing_QNAME = new QName("", "throwing");
    private final static QName _TeamDataTeamPlayersPlayerInjured_QNAME = new QName("", "injured");
    private final static QName _TeamDataTeamPlayersPlayerPlayerId_QNAME = new QName("", "player_id");
    private final static QName _TeamDataTeamPlayersPlayerAdaptabilities_QNAME = new QName("", "adaptabilities");
    private final static QName _TeamDataTeamPlayersPlayerDribbling_QNAME = new QName("", "dribbling");
    private final static QName _TeamDataTeamPlayersPlayerNatRank_QNAME = new QName("", "nat_rank");
    private final static QName _TeamDataTeamPlayersPlayerCountryNt_QNAME = new QName("", "country_nt");
    private final static QName _TeamDataTeamPlayersPlayerAssists_QNAME = new QName("", "assists");
    private final static QName _TeamDataTeamPlayersPlayerPositioning_QNAME = new QName("", "positioning");
    private final static QName _TeamDataTeamPlayersPlayerAnticipation_QNAME = new QName("", "anticipation");
    private final static QName _TeamDataTeamPlayersPlayerIntRank_QNAME = new QName("", "int_rank");
    private final static QName _TeamDataTeamPlayersPlayerSideRight_QNAME = new QName("", "side_right");
    private final static QName _TeamDataTeamPlayersPlayerDecisions_QNAME = new QName("", "decisions");
    private final static QName _TeamDataTeamPlayersPlayerMorale_QNAME = new QName("", "morale");
    private final static QName _TeamDataTeamPlayersPlayerValue_QNAME = new QName("", "value");
    private final static QName _TeamDataTeamPlayersPlayerLoanReturnDate_QNAME = new QName("", "loan_return_date");
    private final static QName _TeamDataTeamPlayersPlayerNewBirthDay_QNAME = new QName("", "new_birth_day");
    private final static QName _TeamDataTeamPlayersPlayerPositionFull_QNAME = new QName("", "position_full");
    private final static QName _TeamDataTeamPlayersPlayerHeading_QNAME = new QName("", "heading");
    private final static QName _TeamDataTeamPlayersPlayerConfidence_QNAME = new QName("", "confidence");
    private final static QName _TeamDataTeamPlayersPlayerConcentration_QNAME = new QName("", "concentration");
    private final static QName _TeamDataTeamPlayersPlayerLastTraining_QNAME = new QName("", "last_training");
    private final static QName _TeamDataTeamPlayersPlayerLoanList_QNAME = new QName("", "loan_list");
    private final static QName _TeamDataTeamPlayersPlayerBirthDay_QNAME = new QName("", "birth_day");
    private final static QName _TeamDataTeamPlayersPlayerMarking_QNAME = new QName("", "marking");
    private final static QName _TeamDataTeamPlayersPlayerFuture_QNAME = new QName("", "future");
    private final static QName _TeamDataTeamPlayersPlayerContractRole_QNAME = new QName("", "contract_role");
    private final static QName _TeamDataTeamPlayersPlayerNationalTeams_QNAME = new QName("", "national_teams");
    private final static QName _TeamDataTeamPlayersPlayerHandling_QNAME = new QName("", "handling");
    private final static QName _TeamDataTeamPlayersPlayerTalents_QNAME = new QName("", "talents");
    private final static QName _TeamDataTeamPlayersPlayerAge_QNAME = new QName("", "age");
    private final static QName _TeamDataTeamPlayersPlayerBravery_QNAME = new QName("", "bravery");
    private final static QName _TeamDataTeamPlayersPlayerDoubleNatCountry_QNAME = new QName("", "country");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingFriday2_QNAME = new QName("", "Friday2");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingFriday1_QNAME = new QName("", "Friday1");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingMonday2_QNAME = new QName("", "Monday2");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingThursday1_QNAME = new QName("", "Thursday1");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingMonday3_QNAME = new QName("", "Monday3");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingMonday1_QNAME = new QName("", "Monday1");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingFriday3_QNAME = new QName("", "Friday3");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingWednesday3_QNAME = new QName("", "Wednesday3");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingSaturday2_QNAME = new QName("", "Saturday2");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingSunday1_QNAME = new QName("", "Sunday1");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingWednesday2_QNAME = new QName("", "Wednesday2");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingSaturday1_QNAME = new QName("", "Saturday1");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingThursday3_QNAME = new QName("", "Thursday3");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingSunday3_QNAME = new QName("", "Sunday3");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingThursday2_QNAME = new QName("", "Thursday2");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingSaturday3_QNAME = new QName("", "Saturday3");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingSunday2_QNAME = new QName("", "Sunday2");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingWednesday1_QNAME = new QName("", "Wednesday1");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingTuesday1_QNAME = new QName("", "Tuesday1");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingTuesday2_QNAME = new QName("", "Tuesday2");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingTuesday3_QNAME = new QName("", "Tuesday3");
    private final static QName _TeamDataTeamPlayersPlayerWeeklyTrainingLastChanged_QNAME = new QName("", "last_changed");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.marcocarettoni.Footstar.xml.model.team
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TeamData }
     * 
     */
    public TeamData createTeamData() {
        return new TeamData();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers }
     * 
     */
    public TeamData.TeamPlayers createTeamDataTeamPlayers() {
        return new TeamData.TeamPlayers();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player }
     * 
     */
    public TeamData.TeamPlayers.Player createTeamDataTeamPlayersPlayer() {
        return new TeamData.TeamPlayers.Player();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.NationalTeams }
     * 
     */
    public TeamData.TeamPlayers.Player.NationalTeams createTeamDataTeamPlayersPlayerNationalTeams() {
        return new TeamData.TeamPlayers.Player.NationalTeams();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Talents }
     * 
     */
    public TeamData.TeamPlayers.Player.Talents createTeamDataTeamPlayersPlayerTalents() {
        return new TeamData.TeamPlayers.Player.Talents();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Adaptabilities }
     * 
     */
    public TeamData.TeamPlayers.Player.Adaptabilities createTeamDataTeamPlayersPlayerAdaptabilities() {
        return new TeamData.TeamPlayers.Player.Adaptabilities();
    }

    /**
     * Create an instance of {@link TeamData.BTeam }
     * 
     */
    public TeamData.BTeam createTeamDataBTeam() {
        return new TeamData.BTeam();
    }

    /**
     * Create an instance of {@link TeamData.Stadium }
     * 
     */
    public TeamData.Stadium createTeamDataStadium() {
        return new TeamData.Stadium();
    }

    /**
     * Create an instance of {@link TeamData.WeeklyTraining }
     * 
     */
    public TeamData.WeeklyTraining createTeamDataWeeklyTraining() {
        return new TeamData.WeeklyTraining();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.SideLeft }
     * 
     */
    public TeamData.TeamPlayers.Player.SideLeft createTeamDataTeamPlayersPlayerSideLeft() {
        return new TeamData.TeamPlayers.Player.SideLeft();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.SideRight }
     * 
     */
    public TeamData.TeamPlayers.Player.SideRight createTeamDataTeamPlayersPlayerSideRight() {
        return new TeamData.TeamPlayers.Player.SideRight();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.SideCenter }
     * 
     */
    public TeamData.TeamPlayers.Player.SideCenter createTeamDataTeamPlayersPlayerSideCenter() {
        return new TeamData.TeamPlayers.Player.SideCenter();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.BirthCity }
     * 
     */
    public TeamData.TeamPlayers.Player.BirthCity createTeamDataTeamPlayersPlayerBirthCity() {
        return new TeamData.TeamPlayers.Player.BirthCity();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Injured }
     * 
     */
    public TeamData.TeamPlayers.Player.Injured createTeamDataTeamPlayersPlayerInjured() {
        return new TeamData.TeamPlayers.Player.Injured();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Suspended }
     * 
     */
    public TeamData.TeamPlayers.Player.Suspended createTeamDataTeamPlayersPlayerSuspended() {
        return new TeamData.TeamPlayers.Player.Suspended();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.SuspendedInt }
     * 
     */
    public TeamData.TeamPlayers.Player.SuspendedInt createTeamDataTeamPlayersPlayerSuspendedInt() {
        return new TeamData.TeamPlayers.Player.SuspendedInt();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Future }
     * 
     */
    public TeamData.TeamPlayers.Player.Future createTeamDataTeamPlayersPlayerFuture() {
        return new TeamData.TeamPlayers.Player.Future();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Confidence }
     * 
     */
    public TeamData.TeamPlayers.Player.Confidence createTeamDataTeamPlayersPlayerConfidence() {
        return new TeamData.TeamPlayers.Player.Confidence();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Experience }
     * 
     */
    public TeamData.TeamPlayers.Player.Experience createTeamDataTeamPlayersPlayerExperience() {
        return new TeamData.TeamPlayers.Player.Experience();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Value }
     * 
     */
    public TeamData.TeamPlayers.Player.Value createTeamDataTeamPlayersPlayerValue() {
        return new TeamData.TeamPlayers.Player.Value();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Wage }
     * 
     */
    public TeamData.TeamPlayers.Player.Wage createTeamDataTeamPlayersPlayerWage() {
        return new TeamData.TeamPlayers.Player.Wage();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.WeeklyTraining }
     * 
     */
    public TeamData.TeamPlayers.Player.WeeklyTraining createTeamDataTeamPlayersPlayerWeeklyTraining() {
        return new TeamData.TeamPlayers.Player.WeeklyTraining();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.DoubleNat }
     * 
     */
    public TeamData.TeamPlayers.Player.DoubleNat createTeamDataTeamPlayersPlayerDoubleNat() {
        return new TeamData.TeamPlayers.Player.DoubleNat();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.NationalTeams.Country }
     * 
     */
    public TeamData.TeamPlayers.Player.NationalTeams.Country createTeamDataTeamPlayersPlayerNationalTeamsCountry() {
        return new TeamData.TeamPlayers.Player.NationalTeams.Country();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Talents.Talent }
     * 
     */
    public TeamData.TeamPlayers.Player.Talents.Talent createTeamDataTeamPlayersPlayerTalentsTalent() {
        return new TeamData.TeamPlayers.Player.Talents.Talent();
    }

    /**
     * Create an instance of {@link TeamData.TeamPlayers.Player.Adaptabilities.Adaptability }
     * 
     */
    public TeamData.TeamPlayers.Player.Adaptabilities.Adaptability createTeamDataTeamPlayersPlayerAdaptabilitiesAdaptability() {
        return new TeamData.TeamPlayers.Player.Adaptabilities.Adaptability();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "favorite_foot", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerFavoriteFoot(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerFavoriteFoot_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transfer_list", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerTransferList(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerTransferList_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "strength", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerStrength(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerStrength_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "birth_month", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerBirthMonth(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerBirthMonth_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "release", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerRelease(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerRelease_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "short_passes", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerShortPasses(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerShortPasses_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "team_id", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerTeamId(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerTeamId_QNAME, Integer.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "flair", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerFlair(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerFlair_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Experience }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "experience", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Experience> createTeamDataTeamPlayersPlayerExperience(TeamData.TeamPlayers.Player.Experience value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Experience>(_TeamDataTeamPlayersPlayerExperience_QNAME, TeamData.TeamPlayers.Player.Experience.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "crosses", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerCrosses(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerCrosses_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "consistency", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerConsistency(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerConsistency_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "birth_year", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerBirthYear(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerBirthYear_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "influence", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerInfluence(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerInfluence_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reflexes", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerReflexes(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerReflexes_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acceleration", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerAcceleration(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerAcceleration_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "out_of_area", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerOutOfArea(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerOutOfArea_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "first_touch", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerFirstTouch(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerFirstTouch_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fitness", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerFitness(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerFitness_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "long_shots", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerLongShots(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerLongShots_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "player_name", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerPlayerName(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerPlayerName_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creativity", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerCreativity(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerCreativity_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "skills_week", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerSkillsWeek(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerSkillsWeek_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "new_birth_year", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerNewBirthYear(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerNewBirthYear_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Wage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wage", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Wage> createTeamDataTeamPlayersPlayerWage(TeamData.TeamPlayers.Player.Wage value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Wage>(_TeamDataTeamPlayersPlayerWage_QNAME, TeamData.TeamPlayers.Player.Wage.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "goals", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerGoals(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerGoals_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.SideLeft }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "side_left", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.SideLeft> createTeamDataTeamPlayersPlayerSideLeft(TeamData.TeamPlayers.Player.SideLeft value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.SideLeft>(_TeamDataTeamPlayersPlayerSideLeft_QNAME, TeamData.TeamPlayers.Player.SideLeft.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assists_career", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerAssistsCareer(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerAssistsCareer_QNAME, Integer.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last_login", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerLastLogin(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerLastLogin_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "adapt", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerAdapt(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerAdapt_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contract", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerContract(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerContract_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.SuspendedInt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "suspended_int", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.SuspendedInt> createTeamDataTeamPlayersPlayerSuspendedInt(TeamData.TeamPlayers.Player.SuspendedInt value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.SuspendedInt>(_TeamDataTeamPlayersPlayerSuspendedInt_QNAME, TeamData.TeamPlayers.Player.SuspendedInt.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.SideCenter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "side_center", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.SideCenter> createTeamDataTeamPlayersPlayerSideCenter(TeamData.TeamPlayers.Player.SideCenter value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.SideCenter>(_TeamDataTeamPlayersPlayerSideCenter_QNAME, TeamData.TeamPlayers.Player.SideCenter.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "team_name", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerTeamName(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerTeamName_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Suspended }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "suspended", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Suspended> createTeamDataTeamPlayersPlayerSuspended(TeamData.TeamPlayers.Player.Suspended value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Suspended>(_TeamDataTeamPlayersPlayerSuspended_QNAME, TeamData.TeamPlayers.Player.Suspended.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "registration_date", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerRegistrationDate(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerRegistrationDate_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nationality", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerNationality(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerNationality_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_id", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Long> createTeamDataTeamPlayersPlayerUserId(Long value) {
        return new JAXBElement<Long>(_TeamDataTeamPlayersPlayerUserId_QNAME, Long.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "goals_career", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerGoalsCareer(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerGoalsCareer_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "position", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerPosition(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerPosition_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nt_squad", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerNtSquad(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerNtSquad_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "agility", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerAgility(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerAgility_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "command_of_area", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerCommandOfArea(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerCommandOfArea_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loan_to", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerLoanTo(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerLoanTo_QNAME, Integer.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tackling", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerTackling(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerTackling_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.BirthCity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "birth_city", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.BirthCity> createTeamDataTeamPlayersPlayerBirthCity(TeamData.TeamPlayers.Player.BirthCity value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.BirthCity>(_TeamDataTeamPlayersPlayerBirthCity_QNAME, TeamData.TeamPlayers.Player.BirthCity.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.DoubleNat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "double_nat", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.DoubleNat> createTeamDataTeamPlayersPlayerDoubleNat(TeamData.TeamPlayers.Player.DoubleNat value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.DoubleNat>(_TeamDataTeamPlayersPlayerDoubleNat_QNAME, TeamData.TeamPlayers.Player.DoubleNat.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jumping", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerJumping(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerJumping_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "composure", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerComposure(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerComposure_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loan_from", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerLoanFrom(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerLoanFrom_QNAME, Integer.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last_contract_date", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerLastContractDate(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerLastContractDate_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "technique", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerTechnique(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerTechnique_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "set_pieces", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerSetPieces(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerSetPieces_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "long_passes", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerLongPasses(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerLongPasses_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date_last_training", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerDateLastTraining(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerDateLastTraining_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "speed", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerSpeed(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerSpeed_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "game_vision", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerGameVision(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerGameVision_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "youth_team", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerYouthTeam(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerYouthTeam_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.WeeklyTraining }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "weekly_training", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.WeeklyTraining> createTeamDataTeamPlayersPlayerWeeklyTraining(TeamData.TeamPlayers.Player.WeeklyTraining value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.WeeklyTraining>(_TeamDataTeamPlayersPlayerWeeklyTraining_QNAME, TeamData.TeamPlayers.Player.WeeklyTraining.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "finishing", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerFinishing(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerFinishing_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "throwing", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerThrowing(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerThrowing_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Injured }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "injured", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Injured> createTeamDataTeamPlayersPlayerInjured(TeamData.TeamPlayers.Player.Injured value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Injured>(_TeamDataTeamPlayersPlayerInjured_QNAME, TeamData.TeamPlayers.Player.Injured.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "player_id", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Long> createTeamDataTeamPlayersPlayerPlayerId(Long value) {
        return new JAXBElement<Long>(_TeamDataTeamPlayersPlayerPlayerId_QNAME, Long.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Adaptabilities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "adaptabilities", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Adaptabilities> createTeamDataTeamPlayersPlayerAdaptabilities(TeamData.TeamPlayers.Player.Adaptabilities value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Adaptabilities>(_TeamDataTeamPlayersPlayerAdaptabilities_QNAME, TeamData.TeamPlayers.Player.Adaptabilities.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dribbling", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerDribbling(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerDribbling_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nat_rank", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerNatRank(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerNatRank_QNAME, Integer.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country_nt", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerCountryNt(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerCountryNt_QNAME, Integer.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assists", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerAssists(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerAssists_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "positioning", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerPositioning(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerPositioning_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "anticipation", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerAnticipation(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerAnticipation_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "int_rank", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerIntRank(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerIntRank_QNAME, Integer.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.SideRight }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "side_right", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.SideRight> createTeamDataTeamPlayersPlayerSideRight(TeamData.TeamPlayers.Player.SideRight value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.SideRight>(_TeamDataTeamPlayersPlayerSideRight_QNAME, TeamData.TeamPlayers.Player.SideRight.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "decisions", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerDecisions(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerDecisions_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "morale", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerMorale(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerMorale_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Value> createTeamDataTeamPlayersPlayerValue(TeamData.TeamPlayers.Player.Value value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Value>(_TeamDataTeamPlayersPlayerValue_QNAME, TeamData.TeamPlayers.Player.Value.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loan_return_date", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerLoanReturnDate(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerLoanReturnDate_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "new_birth_day", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerNewBirthDay(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerNewBirthDay_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "position_full", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerPositionFull(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerPositionFull_QNAME, String.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "heading", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerHeading(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerHeading_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Confidence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "confidence", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Confidence> createTeamDataTeamPlayersPlayerConfidence(TeamData.TeamPlayers.Player.Confidence value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Confidence>(_TeamDataTeamPlayersPlayerConfidence_QNAME, TeamData.TeamPlayers.Player.Confidence.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "concentration", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerConcentration(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerConcentration_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last_training", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Byte> createTeamDataTeamPlayersPlayerLastTraining(Byte value) {
        return new JAXBElement<Byte>(_TeamDataTeamPlayersPlayerLastTraining_QNAME, Byte.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loan_list", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerLoanList(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerLoanList_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "birth_day", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerBirthDay(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerBirthDay_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "marking", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerMarking(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerMarking_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Future }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "future", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Future> createTeamDataTeamPlayersPlayerFuture(TeamData.TeamPlayers.Player.Future value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Future>(_TeamDataTeamPlayersPlayerFuture_QNAME, TeamData.TeamPlayers.Player.Future.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contract_role", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerContractRole(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerContractRole_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.NationalTeams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "national_teams", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.NationalTeams> createTeamDataTeamPlayersPlayerNationalTeams(TeamData.TeamPlayers.Player.NationalTeams value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.NationalTeams>(_TeamDataTeamPlayersPlayerNationalTeams_QNAME, TeamData.TeamPlayers.Player.NationalTeams.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "handling", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerHandling(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerHandling_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeamData.TeamPlayers.Player.Talents }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "talents", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<TeamData.TeamPlayers.Player.Talents> createTeamDataTeamPlayersPlayerTalents(TeamData.TeamPlayers.Player.Talents value) {
        return new JAXBElement<TeamData.TeamPlayers.Player.Talents>(_TeamDataTeamPlayersPlayerTalents_QNAME, TeamData.TeamPlayers.Player.Talents.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "age", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerAge(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerAge_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bravery", scope = TeamData.TeamPlayers.Player.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerBravery(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerBravery_QNAME, Short.class, TeamData.TeamPlayers.Player.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country", scope = TeamData.TeamPlayers.Player.DoubleNat.class)
    public JAXBElement<Integer> createTeamDataTeamPlayersPlayerDoubleNatCountry(Integer value) {
        return new JAXBElement<Integer>(_TeamDataTeamPlayersPlayerDoubleNatCountry_QNAME, Integer.class, TeamData.TeamPlayers.Player.DoubleNat.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Friday2", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingFriday2(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingFriday2_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Friday1", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingFriday1(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingFriday1_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Monday2", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingMonday2(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingMonday2_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Thursday1", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingThursday1(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingThursday1_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Monday3", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingMonday3(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingMonday3_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Monday1", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingMonday1(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingMonday1_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Friday3", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingFriday3(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingFriday3_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Wednesday3", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingWednesday3(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingWednesday3_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Saturday2", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingSaturday2(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingSaturday2_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sunday1", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingSunday1(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingSunday1_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Wednesday2", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingWednesday2(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingWednesday2_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Saturday1", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingSaturday1(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingSaturday1_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Thursday3", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingThursday3(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingThursday3_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sunday3", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingSunday3(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingSunday3_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Thursday2", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingThursday2(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingThursday2_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Saturday3", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingSaturday3(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingSaturday3_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sunday2", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingSunday2(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingSunday2_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Wednesday1", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingWednesday1(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingWednesday1_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tuesday1", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingTuesday1(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingTuesday1_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tuesday2", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingTuesday2(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingTuesday2_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tuesday3", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<Short> createTeamDataTeamPlayersPlayerWeeklyTrainingTuesday3(Short value) {
        return new JAXBElement<Short>(_TeamDataTeamPlayersPlayerWeeklyTrainingTuesday3_QNAME, Short.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last_changed", scope = TeamData.TeamPlayers.Player.WeeklyTraining.class)
    public JAXBElement<String> createTeamDataTeamPlayersPlayerWeeklyTrainingLastChanged(String value) {
        return new JAXBElement<String>(_TeamDataTeamPlayersPlayerWeeklyTrainingLastChanged_QNAME, String.class, TeamData.TeamPlayers.Player.WeeklyTraining.class, value);
    }

}
